---
- hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Check if Docker Daemon Exists
      stat: path=/etc/init.d/docker
      register: docker_installed

- name: Install Docker if necessary
  import_playbook: docker_setup.yml
  when: docker_installed.stat.islnk is not defined


- hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Deploying a systemd service that will create the container
      copy:
        src: .service
        dest: /etc/systemd/system/botify.service

    - name: Starts the service 
      systemd: name=botify.service state=restarted enabled=yes